baseURL = "http://firetowerproject.org/"
languageCode = "en-us"
title = "Firetower Project"
theme = "ananke"

[params]
  description = "Firetower Project"
  # featured_image = "/images/Firetower_project_logo2.png"
